version: '2'
services:
  vault:
    image: vault
    container_name: vault
    ports:
      - "443:443"
    restart: always
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
      - ./volumes/cert:/vault/cert
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/config.hcl

networks:
  default:
    ipam:
      config:
        - subnet: 10.2.0.0/16
