---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: jianmu
    name: jianmu
  name: jianmu

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jianmu-admin
  namespace: jianmu

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jianmu-admin-cluster-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list","create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jianmu-admin-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: jianmu-admin
    namespace: jianmu
roleRef:
  kind: ClusterRole
  name: jianmu-admin-cluster-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jianmu-admin-role
  namespace: jianmu
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jianmu-admin-role-binding
  namespace: jianmu
subjects:
  - kind: ServiceAccount
    name: jianmu-admin
    namespace: jianmu
roleRef:
  kind: Role
  name: jianmu-admin-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ci-server
  name: ci-server
  namespace: jianmu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ci-server
    spec:
      serviceAccountName: jianmu-admin
      containers:
      - command:
        - /wait-for-it.sh
        - jianmu-mysql:3306
        - -t
        - "0"
        - --
        - java
        - -Duser.timezone=Asia/Shanghai
        - -cp
        - /app/resources:/app/classes:/app/libs/*
        - dev.jianmu.api.SpringbootApp
        ports:
          - containerPort: 8081
            protocol: TCP
        env:
        - name: JIANMU_API_ADMINPASSWD
          value: "123456"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "123456"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://jianmu-mysql:3306/jianmu?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: JIANMU_WORKER_TYPE
          value: embedded_kube
        - name: JIANMU_WORKER_K8S_NAMESPACE
          value: jianmu
        image: jianmudev/jianmu-ci-server:v3.0.0-alpha.4
        name: ci-server
        resources: {}
        volumeMounts:
        - mountPath: /task_log
          name: ci-server-claim1
        - mountPath: /workflow_log
          name: ci-server-claim2
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      volumes:
      - name: ci-server-claim0
        persistentVolumeClaim:
          claimName: ci-server-claim0
      - name: ci-server-claim1
        persistentVolumeClaim:
          claimName: ci-server-claim1
      - name: ci-server-claim2
        persistentVolumeClaim:
          claimName: ci-server-claim2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: jianmu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: jianmudev/jianmu-ci-ui:v3.0.0-alpha.4
        name: web
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        resources: {}
      restartPolicy: Always
      dnsPolicy: ClusterFirst

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jianmu-mysql
  name: jianmu-mysql
  namespace: jianmu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jianmu-mysql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: jianmu-mysql
    spec:
      containers:
      - args:
        - --init-connect=SET NAMES utf8
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --max-connections=1200
        - --max-user-connections=1000
        env:
        - name: MYSQL_DATABASE
          value: jianmu
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: TZ
          value: Asia/Shanghai
        image: mysql:8
        name: jianmu-mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
      restartPolicy: Always
      dnsPolicy: ClusterFirst

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ci-server
  name: ci-server
  namespace: jianmu
spec:
  ports:
  - name: headless
    protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    app: ci-server

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
  namespace: jianmu
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30180
  selector:
    app: web
  type: NodePort
  sessionAffinity: ClientIP
  externalTrafficPolicy: Cluster
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jianmu-mysql
  name: jianmu-mysql
  namespace: jianmu
spec:
  ports:
  - name: "3306"
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: jianmu-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ci-server-claim0
  name: ci-server-claim0
  namespace: jianmu
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ci-server-claim1
  name: ci-server-claim1
  namespace: jianmu
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ci-server-claim2
  name: ci-server-claim2
  namespace: jianmu
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
